<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $lessons = [
            [
                'course_id' => 1,
                'title' => 'Web Application & Software Architecture',
                'number' => 1,
                'duration' => 7,
                'video_url' => 'https://www.youtube.com/watch?v=Sklc_fQBmcs',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'An Introduction to Microservice Principles and Concepts',
                'number' => 2,
                'duration' => 3,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'Running Tests',
                'number' => 3,
                'duration' => 4,
                'video_url' => 'https://www.youtube.com/watch?v=eZ74x6dVYes',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/5.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'Microservice Architecture: Practical Implementation',
                'number' => 4,
                'duration' => 6,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/3.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'Grokking the System Design Interview',
                'number' => 5,
                'duration' => 5,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/4.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'The Good Parts of AWS: Cutting Through the Clutter',
                'number' => 6,
                'duration' => 3,
                'video_url' => 'https://www.youtube.com/watch?v=u21W_tfPVrY',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/5.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'Using JSX',
                'number' => 7,
                'duration' => 7,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'Nesting Elements Extra Credit Solution',
                'number' => 8,
                'duration' => 9,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'Clone and Setup',
                'number' => 9,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=ShcR4Zfc6Dw',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/3.md')),
            ],
            [
                'course_id' => 1,
                'title' => 'File Structure',
                'number' => 10,
                'duration' => 13,
                'video_url' => 'https://www.youtube.com/watch?v=yJ5agkia4o8',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/4.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Example Runthrough',
                'number' => 1,
                'duration' => 8,
                'video_url' => 'https://www.youtube.com/watch?v=-MTSQjw5DrM',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Basic JS "Hello World"',
                'number' => 2,
                'duration' => 6,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Creating Custom Components',
                'number' => 3,
                'duration' => 6,
                'video_url' => 'https://www.youtube.com/watch?v=OzDG68VvPxY',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/3.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Render JSX From Functions Solution',
                'number' => 4,
                'duration' => 2,
                'video_url' => 'https://www.youtube.com/watch?v=UgEaJBz3bjY',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/4.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'JSX Extra Credit Solution 02',
                'number' => 5,
                'duration' => 3,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/5.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Styling',
                'number' => 6,
                'duration' => 43,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Break Time',
                'number' => 7,
                'duration' => 4,
                'video_url' => 'https://www.youtube.com/watch?v=oHtR5YSPLjo',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Form Basics',
                'number' => 8,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/3.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Rendering Arrays',
                'number' => 9,
                'duration' => 31,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/4.md')),
            ],
            [
                'course_id' => 2,
                'title' => 'Render Arrays Solution',
                'number' => 10,
                'duration' => 23,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/5.md')),
            ],
            [
                'course_id' => 3,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 3,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 4,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 4,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 5,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 5,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 6,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 6,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 7,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 7,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 8,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 8,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 9,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 9,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 10,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 10,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 11,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 11,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 12,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 12,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 13,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 13,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 14,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 14,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 15,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 15,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
            [
                'course_id' => 16,
                'title' => 'Form Basics',
                'number' => 1,
                'duration' => 12,
                'video_url' => 'https://www.youtube.com/watch?v=-txKSRn0qeA',
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/1.md')),
            ],
            [
                'course_id' => 16,
                'title' => 'Render Arrays Solution',
                'number' => 2,
                'duration' => 22,
                'video_url' => null,
                'text_content' => file_get_contents(database_path('seeders/lesson_text_contents/2.md')),
            ],
        ];

        DB::table('lessons')->insert($lessons);
    }
}
